"""coherence de l acteur du journal

Revision ID: 02993885ef42
Revises: 0b965007d3d8
Create Date: 2026-08-05 23:04:26.732976+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # ajouté à la main : l'autogénération n'en avait pas besoin


# revision identifiers, used by Alembic.
revision: str = "02993885ef42"
down_revision: Union[str, Sequence[str], None] = "0b965007d3d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_audit_log_system_actor_has_no_user"),
        "audit_log",
        "(actor_kind = 'system') = (actor_user_id IS NULL)",
    )
    # ### end Alembic commands ###

    # Ajouté à la main. `now()` renvoie l'heure de début de transaction :
    # toutes les lignes écrites dans la même transaction portaient le même
    # horodatage, et le journal ne pouvait pas dire laquelle a précédé l'autre.
    op.alter_column("audit_log", "occurred_at", server_default=sa.text("clock_timestamp()"))


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column("audit_log", "occurred_at", server_default=sa.text("now()"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_audit_log_system_actor_has_no_user"), "audit_log", type_="check")
    # ### end Alembic commands ###
