"""Periode de grace de l abonnement

Revision ID: 072af217f16b
Revises: fbfafa1993ee
Create Date: 2026-08-13 04:20:01.525541+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "072af217f16b"
down_revision: Union[str, Sequence[str], None] = "fbfafa1993ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("business", sa.Column("grace_ends_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "business", sa.Column("grace_warned_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "business",
        sa.Column(
            "suspended_reason",
            sa.Enum(
                "paused_by_business",
                "grace_expired",
                name="suspension_reason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
    )
    op.create_index("ix_business_grace_ends_at", "business", ["grace_ends_at"], unique=False)

    # **Avant la contrainte, jamais après.** Les commerces déjà suspendus l'ont
    # tous été par leur propre décision — c'était le seul chemin qui existait —
    # et sans ce remplissage la contrainte les refuse en bloc.
    op.execute(
        "UPDATE business SET suspended_reason = 'paused_by_business' "
        "WHERE status = 'suspended' AND suspended_reason IS NULL"
    )

    op.create_check_constraint(
        op.f("ck_business_suspendu_dit_pourquoi"),
        "business",
        "(status = 'suspended') = (suspended_reason IS NOT NULL)",
    )

    # Écrit à la main : une valeur ajoutée à une énumération applicative ne
    # change aucune colonne, seulement la liste d'une contrainte, et
    # l'autogénération ne compare pas les listes. Sans ces lignes, la première
    # préférence posée sur l'un des deux nouveaux genres serait refusée.
    op.drop_constraint("notification_kind", "notification_preference", type_="check")
    op.create_check_constraint(
        "notification_kind",
        "notification_preference",
        "kind IN ('booking_approved', 'booking_declined', 'booking_cancelled_by_business', 'publication_reminder', 'publication_approved', 'publication_resubmit', 'booking_to_review', 'subscription_grace_ending', 'subscription_ended')",
    )
    # **Le troisième CHECK de cette migration, et le troisième oublié.** Toute
    # énumération applicative se rend en VARCHAR + CHECK ; en ajouter une
    # valeur ne change aucune colonne, et l'autogénération ne compare pas les
    # listes. Sans ces lignes, le planificateur ne peut pas créer le balayage,
    # et il échoue au démarrage du worker.
    op.drop_constraint("job_type", "job", type_="check")
    op.create_check_constraint(
        "job_type",
        "job",
        "job_type IN ('token_refresh', 'metrics_refresh', 'booking_hold_sweep', 'collaboration_deadline_sweep', 'collaboration_reminder_sweep', 'link_click_purge_sweep', 'subscription_grace_sweep')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM job WHERE job_type = 'subscription_grace_sweep'")
    op.drop_constraint("job_type", "job", type_="check")
    op.create_check_constraint("job_type", "job", "job_type IN ('token_refresh', 'metrics_refresh', 'booking_hold_sweep', 'collaboration_deadline_sweep', 'collaboration_reminder_sweep', 'link_click_purge_sweep')")

    # Les préférences posées sur les deux nouveaux genres partent avec eux :
    # les garder ferait échouer la contrainte restreinte, et une préférence
    # sur un genre qui n'existe plus ne veut rien dire.
    op.execute(
        "DELETE FROM notification_preference "
        "WHERE kind IN ('subscription_grace_ending', 'subscription_ended')"
    )
    op.drop_constraint("notification_kind", "notification_preference", type_="check")
    op.create_check_constraint(
        "notification_kind",
        "notification_preference",
        "kind IN ('booking_approved', 'booking_declined', 'booking_cancelled_by_business', 'publication_reminder', 'publication_approved', 'publication_resubmit', 'booking_to_review')",
    )

    op.drop_constraint(op.f("ck_business_suspendu_dit_pourquoi"), "business", type_="check")
    op.drop_index("ix_business_grace_ends_at", table_name="business")
    op.drop_column("business", "suspended_reason")
    op.drop_column("business", "grace_warned_at")
    op.drop_column("business", "grace_ends_at")
    # ### end Alembic commands ###
