"""authentification

Revision ID: 0b965007d3d8
Revises: beb4bcbc9378
Create Date: 2026-08-05 22:41:17.414886+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b965007d3d8"
down_revision: Union[str, Sequence[str], None] = "beb4bcbc9378"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_refresh_token_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_token")),
    )
    op.create_index("ix_refresh_token_expires_at", "refresh_token", ["expires_at"], unique=False)
    op.create_index(
        "ix_refresh_token_user_id_revoked_at",
        "refresh_token",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.add_column("app_user", sa.Column("password_hash", sa.Text(), nullable=True))
    # Note pour une reprise ultérieure : ce CHECK est validé contre les lignes
    # existantes. Sur une base déjà peuplée de comptes sans empreinte, il
    # faudrait les renseigner ou les anonymiser avant. Ici la table est vide.
    op.create_check_constraint(
        op.f("ck_app_user_password_unless_anonymized"),
        "app_user",
        "status = 'anonymized' OR password_hash IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_app_user_password_unless_anonymized"), "app_user", type_="check")
    op.drop_column("app_user", "password_hash")
    op.drop_index("ix_refresh_token_user_id_revoked_at", table_name="refresh_token")
    op.drop_index("ix_refresh_token_expires_at", table_name="refresh_token")
    op.drop_table("refresh_token")
    # ### end Alembic commands ###
