"""le lien facebook du salon

Revision ID: 0dd636498adf
Revises: 59427812e134
Create Date: 2026-09-03 21:39:49.800151+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dd636498adf"
down_revision: Union[str, Sequence[str], None] = "59427812e134"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("business", sa.Column("facebook_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("business", "facebook_url")
    # ### end Alembic commands ###
