"""le quartier du commerce

Revision ID: 13cf2b9349d9
Revises: 1e385c5a2f9e
Nullable et sans remplissage : aucun commerce existant n'a de quartier, et en
inventer un depuis son adresse serait exactement ce que la liste fermee existe
pour eviter. Ils le declareront.

Create Date: 2026-08-16 17:29:20.451135+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13cf2b9349d9"
down_revision: Union[str, Sequence[str], None] = "1e385c5a2f9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "business",
        sa.Column(
            "neighborhood",
            sa.Enum(
                "wynwood",
                "brickell",
                "south_beach",
                "little_havana",
                "design_district",
                "coral_gables",
                "midtown",
                "edgewater",
                "coconut_grove",
                name="neighborhood",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("business", "neighborhood")
    # ### end Alembic commands ###
