"""Reprise d un compte commerce par l administration

Revision ID: 174635261184
Revises: 072af217f16b
Create Date: 2026-08-13 13:09:23.525065+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "174635261184"
down_revision: Union[str, Sequence[str], None] = "072af217f16b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_support_access",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("admin_user_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_business_support_access_close_apres_ouverture"),
        ),
        sa.CheckConstraint(
            "expires_at > started_at",
            name=op.f("ck_business_support_access_expire_apres_ouverture"),
        ),
        sa.CheckConstraint(
            "length(reason) <= 500", name=op.f("ck_business_support_access_motif_borne")
        ),
        sa.CheckConstraint(
            "length(trim(reason)) > 0", name=op.f("ck_business_support_access_motif_non_vide")
        ),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["app_user.id"],
            name=op.f("fk_business_support_access_admin_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_business_support_access_business_id_business"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_support_access")),
    )
    op.create_index(
        "ix_business_support_access_business_id_started_at",
        "business_support_access",
        ["business_id", "started_at"],
        unique=False,
    )
    # Écrit à la main : une valeur ajoutée à une énumération applicative ne
    # change aucune colonne, seulement la liste d'une contrainte, et
    # l'autogénération ne compare pas les listes. Troisième migration d'affilée
    # où elle manquait à la relecture et où la suite l'a dit.
    op.drop_constraint("notification_kind", "notification_preference", type_="check")
    op.create_check_constraint(
        "notification_kind",
        "notification_preference",
        "kind IN ('booking_approved', 'booking_declined', 'booking_cancelled_by_business', 'publication_reminder', 'publication_approved', 'publication_resubmit', 'booking_to_review', 'subscription_grace_ending', 'subscription_ended', 'support_access_started')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM notification_preference WHERE kind = 'support_access_started'")
    op.drop_constraint("notification_kind", "notification_preference", type_="check")
    op.create_check_constraint(
        "notification_kind",
        "notification_preference",
        "kind IN ('booking_approved', 'booking_declined', 'booking_cancelled_by_business', 'publication_reminder', 'publication_approved', 'publication_resubmit', 'booking_to_review', 'subscription_grace_ending', 'subscription_ended')",
    )
    op.drop_index(
        "ix_business_support_access_business_id_started_at", table_name="business_support_access"
    )
    op.drop_table("business_support_access")
    # ### end Alembic commands ###
