"""les favoris d une creatrice

Revision ID: 353367c94661
Revises: e676b29e66b0
Create Date: 2026-08-24 01:27:42.505411+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "353367c94661"
down_revision: Union[str, Sequence[str], None] = "e676b29e66b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creator_favorite",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["catalog_item_id"],
            ["catalog_item.id"],
            name=op.f("fk_creator_favorite_catalog_item_id_catalog_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["app_user.id"],
            name=op.f("fk_creator_favorite_creator_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creator_favorite")),
        sa.UniqueConstraint(
            "creator_id",
            "catalog_item_id",
            name=op.f("uq_creator_favorite_creator_id_catalog_item_id"),
        ),
    )
    op.create_index(
        "ix_creator_favorite_creator_id_created_at",
        "creator_favorite",
        ["creator_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_creator_favorite_creator_id_created_at", table_name="creator_favorite")
    op.drop_table("creator_favorite")
    # ### end Alembic commands ###
