"""dates d abonnement

Revision ID: 3a71b405efa5
Revises: 91dc02e76ebd
Create Date: 2026-08-22 03:39:19.637528+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a71b405efa5"
down_revision: Union[str, Sequence[str], None] = "91dc02e76ebd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("subscription", sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        op.f("ck_subscription_fin_apres_debut"),
        "subscription",
        "started_at IS NULL OR ended_at IS NULL OR ended_at >= started_at",
    )
    # ### end Alembic commands ###

    # **Reprise depuis le journal d'audit, et seulement quand elle est sûre.**
    # La souscription et la résiliation y sont écrites — sur l'entité
    # `business`, avec un statut préfixé `subscription:` — mais rien n'y
    # désigne la ligne d'abonnement. Un commerce qui a souscrit deux fois a
    # deux ouvertures et aucun moyen de les apparier.
    #
    # On ne reprend donc que les commerces qui n'ont **qu'un** abonnement. Les
    # autres restent à `NULL`, ce qui est exact : on ne sait pas. Deviner
    # rendrait une médiane dont personne ne pourrait dire ce qu'elle mesure —
    # exactement ce que ces colonnes existent pour éviter.
    op.execute(
        """
        WITH un_seul AS (
            SELECT business_id FROM subscription GROUP BY business_id HAVING count(*) = 1
        ),
        ouverture AS (
            SELECT entity_id, min(occurred_at) AS le
            FROM audit_log
            WHERE entity_type = 'business' AND to_status LIKE 'subscription:%'
            GROUP BY entity_id
        )
        UPDATE subscription AS s
        SET started_at = ouverture.le
        FROM ouverture, un_seul
        WHERE s.business_id = ouverture.entity_id
          AND s.business_id = un_seul.business_id
        """
    )

    # La fin : le dernier passage vers un statut résilié, même prudence.
    op.execute(
        """
        WITH un_seul AS (
            SELECT business_id FROM subscription GROUP BY business_id HAVING count(*) = 1
        ),
        fermeture AS (
            SELECT entity_id, max(occurred_at) AS le
            FROM audit_log
            WHERE entity_type = 'business' AND to_status = 'subscription:canceled'
            GROUP BY entity_id
        )
        UPDATE subscription AS s
        SET ended_at = fermeture.le
        FROM fermeture, un_seul
        WHERE s.business_id = fermeture.entity_id
          AND s.business_id = un_seul.business_id
          AND s.started_at IS NOT NULL
          AND fermeture.le >= s.started_at
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_subscription_fin_apres_debut"), "subscription", type_="check")
    op.drop_column("subscription", "ended_at")
    op.drop_column("subscription", "started_at")
    # ### end Alembic commands ###
