"""les quatre champs de la preuve verifiee

Revision ID: 3a85195ca1f5
Revises: 671a7158bcc9
Create Date: 2026-08-12 21:09:11.650995+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a85195ca1f5"
down_revision: Union[str, Sequence[str], None] = "671a7158bcc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("proof", sa.Column("platform_media_id", sa.Text(), nullable=True))
    op.add_column("proof", sa.Column("platform_author_id", sa.Text(), nullable=True))
    op.add_column("proof", sa.Column("platform_media_type", sa.Text(), nullable=True))
    op.create_index(
        "uq_proof_platform_media_id",
        "proof",
        ["platform_media_id"],
        unique=True,
        postgresql_where=sa.text("platform_media_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_proof_platform_media_id",
        table_name="proof",
        postgresql_where=sa.text("platform_media_id IS NOT NULL"),
    )
    op.drop_column("proof", "platform_media_type")
    op.drop_column("proof", "platform_author_id")
    op.drop_column("proof", "platform_media_id")
    # ### end Alembic commands ###
