"""archiver une prestation

Revision ID: 4425b8c5812f
Revises: 6291bad03ebe
Create Date: 2026-08-22 16:25:40.176681+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4425b8c5812f"
down_revision: Union[str, Sequence[str], None] = "6291bad03ebe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "catalog_item", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("catalog_item", "archived_at")
    # ### end Alembic commands ###
