"""les trois liens publics du salon

Revision ID: 59427812e134
Revises: 180a1f13cdbb
Create Date: 2026-08-31 03:47:30.034031+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59427812e134'
down_revision: Union[str, Sequence[str], None] = '180a1f13cdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('instagram_url', sa.Text(), nullable=True))
    op.add_column('business', sa.Column('tiktok_url', sa.Text(), nullable=True))
    op.add_column('business', sa.Column('website_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'website_url')
    op.drop_column('business', 'tiktok_url')
    op.drop_column('business', 'instagram_url')
    # ### end Alembic commands ###
