"""Journal des modifications de configuration

Revision ID: 598cee0d8035
Revises: e131756117a0
Create Date: 2026-08-13 17:14:46.227686+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "598cee0d8035"
down_revision: Union[str, Sequence[str], None] = "e131756117a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration_change",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("value_before", sa.Text(), nullable=True),
        sa.Column("value_after", sa.Text(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(field)) > 0", name=op.f("ck_configuration_change_champ_non_vide")
        ),
        sa.CheckConstraint(
            "value_before IS DISTINCT FROM value_after",
            name=op.f("ck_configuration_change_une_modification_change_quelque_chose"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["app_user.id"],
            name=op.f("fk_configuration_change_actor_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configuration_change")),
    )
    op.create_index(
        "ix_configuration_change_entity_id_changed_at",
        "configuration_change",
        ["entity_id", "changed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_configuration_change_entity_id_changed_at", table_name="configuration_change")
    op.drop_table("configuration_change")
    # ### end Alembic commands ###
