"""galerie photos du commerce

Revision ID: 5e0343180f0a
Revises: eb545e31208c
Create Date: 2026-08-12 16:46:11.528113+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e0343180f0a"
down_revision: Union[str, Sequence[str], None] = "eb545e31208c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_photo",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_business_photo_business_photo_position_positive")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_business_photo_business_id_business"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_photo")),
        sa.UniqueConstraint(
            "business_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name="uq_business_photo_position",
        ),
    )
    op.create_index(
        "ix_business_photo_business_position",
        "business_photo",
        ["business_id", "position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_business_photo_business_position", table_name="business_photo")
    op.drop_table("business_photo")
    # ### end Alembic commands ###
