"""ouverture et blocage d une fiche remise

Revision ID: 6291bad03ebe
Revises: 3a71b405efa5
Create Date: 2026-08-22 04:00:52.433818+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6291bad03ebe"
down_revision: Union[str, Sequence[str], None] = "3a71b405efa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "business_handover", sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "business_handover", sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("business_handover", "blocked_at")
    op.drop_column("business_handover", "opened_at")
    # ### end Alembic commands ###
