"""signalement de deplacement pour rien

Le cas inverse de l'absence. Un createur qui ne vient pas est penalise ; un
salon ferme ne l'etait pas, et le createur perdait son creneau sans recours.

Un signalement est une **allegation**, jamais un verdict : il ne compte contre
le salon qu'une fois arbitre. C'est la meme regle que la revue humaine des
contreparties — la mecanique s'arrete et un humain tranche, plutot que de
transformer une parole en sanction automatique.

`abusive_report` rejoint les types d'evenement de fiabilite, avec un poids nul
en configuration. Le mecanisme existe pour que la decision se prenne sur des
chiffres, pas pour punir des le premier jour quelqu'un dont le signalement n'a
pas ete retenu — ce qui n'est pas la meme chose qu'un mensonge.

Revision ID: 671a7158bcc9
Revises: f2c893cd716a
Create Date: 2026-08-12 20:35:19.318578+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "671a7158bcc9"
down_revision: Union[str, Sequence[str], None] = "f2c893cd716a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venue_report",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "rejected",
                name="venue_report_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(status = 'pending') = (decided_at IS NULL AND decided_by_user_id IS NULL)",
            name=op.f("ck_venue_report_decide_a_un_arbitre_et_une_date"),
        ),
        sa.CheckConstraint(
            "note IS NULL OR length(note) <= 500", name=op.f("ck_venue_report_note_bornee")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["booking.id"],
            name=op.f("fk_venue_report_booking_id_booking"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_venue_report_business_id_business"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["app_user.id"],
            name=op.f("fk_venue_report_creator_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_venue_report_decided_by_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venue_report")),
        sa.UniqueConstraint("booking_id", name=op.f("uq_venue_report_booking_id")),
    )
    op.create_index(
        "ix_venue_report_business_id_status",
        "venue_report",
        ["business_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_venue_report_status_reported_at",
        "venue_report",
        ["status", "reported_at"],
        unique=False,
    )
    # **Le type d'evenement est un VARCHAR + CHECK**, jamais un enum natif :
    # alterer un enum natif en migration est un piege dont ce depot se passe.
    # La contrepartie est qu'ajouter une valeur demande de reecrire la
    # contrainte, ce que l'autogeneration ne detecte pas.
    #
    # Sans cette reecriture, l'arbitrage d'un signalement ecarte ne peut pas
    # ecrire son evenement — et l'anti-abus tiendrait dans une intention.
    op.drop_constraint(
        op.f("ck_reliability_event_reliability_event_type"), "reliability_event", type_="check"
    )
    op.create_check_constraint(
        "reliability_event_type",
        "reliability_event",
        sa.column("type").in_(
            [
                "collab_completed",
                "published_on_time",
                "published_late",
                "first_pass_compliant",
                "resubmit_required",
                "no_show",
                "unfulfilled",
                "business_rating",
                "abusive_report",
            ]
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Les evenements d'abus disparaissent avec la contrainte qui les
    # autorisait : les laisser ferait echouer la contrainte restauree.
    op.execute("DELETE FROM reliability_event WHERE type = 'abusive_report'")
    op.drop_constraint(
        op.f("ck_reliability_event_reliability_event_type"), "reliability_event", type_="check"
    )
    op.create_check_constraint(
        "reliability_event_type",
        "reliability_event",
        sa.column("type").in_(
            [
                "collab_completed",
                "published_on_time",
                "published_late",
                "first_pass_compliant",
                "resubmit_required",
                "no_show",
                "unfulfilled",
                "business_rating",
            ]
        ),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_venue_report_status_reported_at", table_name="venue_report")
    op.drop_index("ix_venue_report_business_id_status", table_name="venue_report")
    op.drop_table("venue_report")
    # ### end Alembic commands ###
