"""Boite d envoi des messages

Revision ID: 69097f3c54f7
Revises: 174635261184
Create Date: 2026-08-13 15:06:45.988985+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "69097f3c54f7"
down_revision: Union[str, Sequence[str], None] = "174635261184"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbound_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "email", "push", name="message_channel", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "booking_approved",
                "booking_declined",
                "booking_cancelled_by_business",
                "publication_reminder",
                "publication_approved",
                "publication_resubmit",
                "booking_to_review",
                "subscription_grace_ending",
                "subscription_ended",
                "support_access_started",
                name="notification_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("template_key", sa.Text(), nullable=False),
        sa.Column(
            "values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "run_after",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("skipped_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbound_message_tentatives_positives")),
        sa.CheckConstraint(
            "sent_at IS NULL OR skipped_reason IS NULL",
            name=op.f("ck_outbound_message_pas_parti_et_ecarte"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_outbound_message_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_message")),
    )
    op.create_index(
        "ix_outbound_message_en_attente",
        "outbound_message",
        ["run_after"],
        unique=False,
        postgresql_where=sa.text("sent_at IS NULL AND skipped_reason IS NULL"),
    )
    # **Le quatrième CHECK écrit à la main en quatre migrations.** Toute
    # énumération applicative se rend en VARCHAR + CHECK ; ajouter une valeur ne
    # change aucune colonne, et l'autogénération ne compare pas les listes.
    # Sans ces lignes, le planificateur ne peut pas créer le balayage et le
    # travail de fond échoue au démarrage.
    op.drop_constraint("job_type", "job", type_="check")
    op.create_check_constraint(
        "job_type",
        "job",
        "job_type IN ('token_refresh', 'metrics_refresh', 'booking_hold_sweep', 'collaboration_deadline_sweep', 'collaboration_reminder_sweep', 'link_click_purge_sweep', 'subscription_grace_sweep', 'outbox_sweep')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM job WHERE job_type = 'outbox_sweep'")
    op.drop_constraint("job_type", "job", type_="check")
    op.create_check_constraint(
        "job_type",
        "job",
        "job_type IN ('token_refresh', 'metrics_refresh', 'booking_hold_sweep', 'collaboration_deadline_sweep', 'collaboration_reminder_sweep', 'link_click_purge_sweep', 'subscription_grace_sweep')",
    )
    op.drop_index(
        "ix_outbound_message_en_attente",
        table_name="outbound_message",
        postgresql_where=sa.text("sent_at IS NULL AND skipped_reason IS NULL"),
    )
    op.drop_table("outbound_message")
    # ### end Alembic commands ###
