"""les photos de plateforme partent

Revision ID: 83b10e7d2ed3
Revises: 4425b8c5812f
Create Date: 2026-08-22 17:06:49.976790+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "83b10e7d2ed3"
down_revision: Union[str, Sequence[str], None] = "4425b8c5812f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """La table des médias de plateforme part avec ses lecteurs.

    Elle portait deux choses : les six photos de catégories et les médias de
    l'écran d'accueil. Les seconds sont partis avec la planche v3, qui a retiré
    la vidéo de fond ; les premières n'ont jamais eu de lecteur — les pastilles
    du fil sont des mots traduits, et leurs comptes viennent de la route du fil.

    Les fichiers eux-mêmes restent dans le dépôt d'objets, où la purge les
    reprendra : ce sont des photos de démonstration, régénérées par le semis.
    Ce qui part ici est la table qui prétendait les servir.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("platform_asset")
    # ### end Alembic commands ###


def downgrade() -> None:
    """La table revient vide.

    Les clés qu'elle portait ne se retrouvent pas : elles pointaient vers des
    objets du dépôt que rien n'associe plus à un slug. Le semis les repose, et
    c'est le seul chemin honnête — reconstruire des associations qu'on ne
    connaît plus reviendrait à les inventer.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_asset",
        sa.Column("slug", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("object_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_platform_asset")),
    )
    # ### end Alembic commands ###
