"""anonymisation

Revision ID: 89f621c1f80f
Revises: 02993885ef42
Create Date: 2026-08-05 23:42:09.920737+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89f621c1f80f"
down_revision: Union[str, Sequence[str], None] = "02993885ef42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Ajouté à la main. Une anonymisation qu'un UPDATE peut défaire n'est pas une
# anonymisation. Le trigger interdit les deux façons de la défaire : remettre
# le compte en service, et y réinjecter des données personnelles.
GEL_DU_COMPTE_ANONYMISE = """
CREATE OR REPLACE FUNCTION app_user_reject_deanonymization() RETURNS trigger AS $$
BEGIN
    IF OLD.status = 'anonymized' THEN
        IF NEW.status <> 'anonymized' THEN
            RAISE EXCEPTION 'un compte anonymise ne peut pas etre reactive'
                USING ERRCODE = 'restrict_violation';
        END IF;

        IF NEW.email IS NOT NULL
           OR NEW.phone IS NOT NULL
           OR NEW.password_hash IS NOT NULL THEN
            RAISE EXCEPTION 'un compte anonymise ne peut pas recouvrer ses donnees personnelles'
                USING ERRCODE = 'restrict_violation';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER app_user_stays_anonymized
    BEFORE UPDATE ON app_user
    FOR EACH ROW EXECUTE FUNCTION app_user_reject_deanonymization();
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("social_account", "external_id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("social_account", "handle", existing_type=sa.TEXT(), nullable=True)
    op.create_check_constraint(
        op.f("ck_social_account_identity_erased_together"),
        "social_account",
        "(external_id IS NULL) = (handle IS NULL)",
    )
    op.create_check_constraint(
        op.f("ck_social_account_identity_unless_revoked"),
        "social_account",
        "external_id IS NOT NULL OR status = 'revoked'",
    )
    # ### end Alembic commands ###

    op.execute(GEL_DU_COMPTE_ANONYMISE)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS app_user_reject_deanonymization() CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_social_account_identity_unless_revoked"), "social_account", type_="check"
    )
    op.drop_constraint(
        op.f("ck_social_account_identity_erased_together"), "social_account", type_="check"
    )
    op.alter_column("social_account", "handle", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("social_account", "external_id", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
