"""Photo de profil du createur

Revision ID: 920c338b2626
Revises: 598cee0d8035
Create Date: 2026-08-14 16:00:09.987330+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "920c338b2626"
down_revision: Union[str, Sequence[str], None] = "598cee0d8035"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("social_account", sa.Column("avatar_key", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("social_account", "avatar_key")
    # ### end Alembic commands ###
