"""modele de donnees complet

Revision ID: beb4bcbc9378
Revises:
Create Date: 2026-08-05 21:36:50.242293+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # ajouté à la main : l'autogénération rend geoalchemy2.types.Geography sans importer le module
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "beb4bcbc9378"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Ajouté à la main. Le journal d'audit ne doit pas pouvoir être réécrit : sans
# ce trigger, « immuable » n'est qu'une intention. Le cas TRUNCATE est couvert
# explicitement, il ne déclenche pas les triggers de ligne.
AUDIT_LOG_IMMUTABILITY = """
CREATE OR REPLACE FUNCTION audit_log_reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_log est immuable : % refuse', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_no_update
    BEFORE UPDATE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_reject_mutation();

CREATE TRIGGER audit_log_no_delete
    BEFORE DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_reject_mutation();

CREATE TRIGGER audit_log_no_truncate
    BEFORE TRUNCATE ON audit_log
    FOR EACH STATEMENT EXECUTE FUNCTION audit_log_reject_mutation();
"""


def upgrade() -> None:
    """Upgrade schema."""
    # Ajouté à la main. Une base créée depuis template1 n'a pas PostGIS : les
    # colonnes geography ne peuvent pas être créées sans cette ligne.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "creator",
                "business_member",
                "admin",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column(
            "locale",
            sa.Enum("en", "es", name="locale", native_enum=False, create_constraint=True),
            server_default="en",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "suspended",
                "anonymized",
                name="user_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
    )
    op.create_index(
        "uq_app_user_email_lower", "app_user", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "business",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "beauty",
                "restaurant",
                "museum",
                "fitness",
                "family_activity",
                "other",
                name="business_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column(
            "geo",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "timezone", sa.Text(), server_default=sa.text("'America/New_York'"), nullable=False
        ),
        sa.Column(
            "default_locale",
            sa.Enum("en", "es", name="locale", native_enum=False, create_constraint=True),
            server_default="en",
            nullable=False,
        ),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "onboarding",
                "active",
                "suspended",
                name="business_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="onboarding",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business")),
    )
    op.create_index("ix_business_category_status", "business", ["category", "status"], unique=False)
    op.create_index("ix_business_geo", "business", ["geo"], unique=False, postgresql_using="gist")
    op.create_table(
        "subscription_plan",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "beauty",
                "restaurant",
                "museum",
                "fitness",
                "family_activity",
                "other",
                name="business_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("price_cents", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "billing_interval",
            sa.Enum(
                "monthly",
                "yearly",
                name="billing_interval",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "features",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "price_cents >= 0", name=op.f("ck_subscription_plan_price_cents_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_plan")),
    )
    op.create_table(
        "tier",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "instagram",
                "tiktok",
                "snapchat",
                "youtube",
                name="platform",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "content_format",
            sa.Enum(
                "story",
                "post",
                "reel",
                name="content_format",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("min_followers", sa.Integer(), nullable=False),
        sa.Column("min_reliability_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "min_completed_collabs", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("value_ratio_hint", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "min_completed_collabs >= 0", name=op.f("ck_tier_min_completed_collabs_positive")
        ),
        sa.CheckConstraint("min_followers >= 0", name=op.f("ck_tier_min_followers_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tier")),
        sa.UniqueConstraint(
            "platform", "content_format", name=op.f("uq_tier_platform_content_format")
        ),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.Text(), nullable=True),
        sa.Column("to_status", sa.Text(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "actor_kind",
            sa.Enum(
                "system",
                "creator",
                "business_member",
                "admin",
                name="actor_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["app_user.id"],
            name=op.f("fk_audit_log_actor_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_entity_type_entity_id_occurred_at",
        "audit_log",
        ["entity_type", "entity_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "business_member",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "staff",
                name="business_member_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_business_member_business_id_business"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_business_member_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_member")),
        sa.UniqueConstraint(
            "business_id", "user_id", name=op.f("uq_business_member_business_id_user_id")
        ),
    )
    op.create_table(
        "capacity_exception",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("concurrent_slots", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(start_time IS NULL) = (end_time IS NULL)",
            name=op.f("ck_capacity_exception_time_window_both_or_neither"),
        ),
        sa.CheckConstraint(
            "concurrent_slots IS NULL OR concurrent_slots > 0",
            name=op.f("ck_capacity_exception_concurrent_slots_positive"),
        ),
        sa.CheckConstraint(
            "start_time IS NULL OR start_time < end_time",
            name=op.f("ck_capacity_exception_start_before_end"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_capacity_exception_business_id_business"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capacity_exception")),
        sa.UniqueConstraint(
            "business_id", "date", name=op.f("uq_capacity_exception_business_id_date")
        ),
    )
    op.create_table(
        "capacity_rule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("concurrent_slots", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "concurrent_slots > 0", name=op.f("ck_capacity_rule_concurrent_slots_positive")
        ),
        sa.CheckConstraint("start_time < end_time", name=op.f("ck_capacity_rule_start_before_end")),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name=op.f("ck_capacity_rule_weekday_range")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_capacity_rule_business_id_business"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capacity_rule")),
    )
    op.create_index(
        "ix_capacity_rule_business_id_weekday",
        "capacity_rule",
        ["business_id", "weekday"],
        unique=False,
    )
    op.create_table(
        "catalog_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("parent_item_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_cents", sa.BigInteger(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("requires_booking", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_available", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "import",
                name="catalog_item_source",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="manual",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(requires_booking AND duration_minutes IS NOT NULL) OR (NOT requires_booking AND duration_minutes IS NULL)",
            name=op.f("ck_catalog_item_duration_matches_requires_booking"),
        ),
        sa.CheckConstraint(
            "duration_minutes IS NULL OR duration_minutes > 0",
            name=op.f("ck_catalog_item_duration_minutes_positive"),
        ),
        sa.CheckConstraint("price_cents >= 0", name=op.f("ck_catalog_item_price_cents_positive")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_catalog_item_business_id_business"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_item_id", "business_id"],
            ["catalog_item.id", "catalog_item.business_id"],
            name="fk_catalog_item_parent_business",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_item")),
        sa.UniqueConstraint(
            "id",
            "business_id",
            "requires_booking",
            name=op.f("uq_catalog_item_id_business_id_requires_booking"),
        ),
        sa.UniqueConstraint("id", "business_id", name=op.f("uq_catalog_item_id_business_id")),
    )
    op.create_index(
        "ix_catalog_item_business_id_is_available",
        "catalog_item",
        ["business_id", "is_available"],
        unique=False,
    )
    op.create_table(
        "creator_profile",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column(
            "geo",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column(
            "reliability_score",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="NULL signifie neutre, pas zéro : la condition de score du moteur de paliers est ignorée, pas échouée. Recalculé depuis reliability_event, jamais écrit à la main.",
        ),
        sa.Column(
            "completed_collabs_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_new_creator",
            sa.Boolean(),
            sa.Computed("reliability_score IS NULL", persisted=True),
            nullable=False,
        ),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_collabs_count >= 0",
            name=op.f("ck_creator_profile_completed_collabs_count_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_creator_profile_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_creator_profile")),
    )
    op.create_index(
        "ix_creator_profile_geo", "creator_profile", ["geo"], unique=False, postgresql_using="gist"
    )
    op.create_table(
        "menu_import",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("file_key", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "extracted",
                "under_review",
                "validated",
                "failed",
                name="menu_import_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="uploaded",
            nullable=False,
        ),
        sa.Column("extracted_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_menu_import_business_id_business"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["app_user.id"],
            name=op.f("fk_menu_import_reviewed_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_menu_import")),
    )
    op.create_index(
        "ix_menu_import_business_id_status", "menu_import", ["business_id", "status"], unique=False
    )
    op.create_table(
        "subscription",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "trialing",
                "active",
                "past_due",
                "canceled",
                name="subscription_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stripe_customer_id", sa.Text(), nullable=True),
        sa.Column("stripe_subscription_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_subscription_business_id_business"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["subscription_plan.id"],
            name=op.f("fk_subscription_plan_id_subscription_plan"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription")),
        sa.UniqueConstraint(
            "stripe_subscription_id", name=op.f("uq_subscription_stripe_subscription_id")
        ),
    )
    op.create_index("ix_subscription_business_id", "subscription", ["business_id"], unique=False)
    op.create_table(
        "social_account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "instagram",
                "tiktok",
                "snapchat",
                "youtube",
                name="platform",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("handle", sa.Text(), nullable=False),
        sa.Column("access_token_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("refresh_token_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("granted_scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "expired",
                "revoked",
                name="social_account_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "verified",
                "needs_review",
                "rejected",
                name="verification_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="needs_review",
            nullable=False,
        ),
        sa.Column("verification_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "connected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator_profile.user_id"],
            name=op.f("fk_social_account_creator_id_creator_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_account")),
        sa.UniqueConstraint(
            "platform", "external_id", name=op.f("uq_social_account_platform_external_id")
        ),
    )
    op.create_index("ix_social_account_creator_id", "social_account", ["creator_id"], unique=False)
    op.create_table(
        "tier_offer",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("tier_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_item_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_tier_offer_business_id_business"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["catalog_item_id", "business_id"],
            ["catalog_item.id", "catalog_item.business_id"],
            name="fk_tier_offer_item_business",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tier_id"], ["tier.id"], name=op.f("fk_tier_offer_tier_id_tier"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tier_offer")),
        sa.UniqueConstraint(
            "business_id",
            "tier_id",
            "catalog_item_id",
            name=op.f("uq_tier_offer_business_id_tier_id_catalog_item_id"),
        ),
        sa.UniqueConstraint("id", "business_id", name=op.f("uq_tier_offer_id_business_id")),
    )
    op.create_index(
        "ix_tier_offer_tier_id_is_active", "tier_offer", ["tier_id", "is_active"], unique=False
    )
    op.create_table(
        "booking",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("tier_offer_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_item_id", sa.Uuid(), nullable=False),
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column("requires_booking", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "held",
                "confirmed",
                "consumed",
                "cancelled",
                "no_show",
                "expired",
                name="booking_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="held",
            nullable=False,
        ),
        sa.Column("hold_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("value_cents_snapshot", sa.BigInteger(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'held' OR hold_expires_at IS NOT NULL",
            name=op.f("ck_booking_held_has_hold_expiry"),
        ),
        sa.CheckConstraint(
            "(requires_booking AND starts_at IS NOT NULL AND ends_at IS NOT NULL) OR (NOT requires_booking AND starts_at IS NULL AND ends_at IS NULL)",
            name=op.f("ck_booking_slot_matches_requires_booking"),
        ),
        sa.CheckConstraint(
            "starts_at IS NULL OR ends_at > starts_at", name=op.f("ck_booking_ends_after_starts")
        ),
        sa.CheckConstraint(
            "value_cents_snapshot >= 0", name=op.f("ck_booking_value_cents_snapshot_positive")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_booking_business_id_business"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["catalog_item_id", "business_id", "requires_booking"],
            ["catalog_item.id", "catalog_item.business_id", "catalog_item.requires_booking"],
            name="fk_booking_item_business_requires_booking",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator_profile.user_id"],
            name=op.f("fk_booking_creator_id_creator_profile"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_account.id"],
            name=op.f("fk_booking_social_account_id_social_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tier_offer_id", "business_id"],
            ["tier_offer.id", "tier_offer.business_id"],
            name="fk_booking_offer_business",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking")),
    )
    op.create_index(
        "ix_booking_business_id_starts_at", "booking", ["business_id", "starts_at"], unique=False
    )
    op.create_index(
        "ix_booking_creator_id_created_at",
        "booking",
        ["creator_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_booking_status_hold_expires_at", "booking", ["status", "hold_expires_at"], unique=False
    )
    op.create_table(
        "social_metrics_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("followers_count", sa.Integer(), nullable=False),
        sa.Column("following_count", sa.Integer(), nullable=False),
        sa.Column("media_count", sa.Integer(), nullable=False),
        sa.Column("avg_views", sa.Integer(), nullable=True),
        sa.Column("engagement_rate", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("audience_demographics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "followers_count >= 0", name=op.f("ck_social_metrics_snapshot_followers_count_positive")
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_account.id"],
            name=op.f("fk_social_metrics_snapshot_social_account_id_social_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_metrics_snapshot")),
    )
    op.create_index(
        "ix_social_metrics_snapshot_account_captured",
        "social_metrics_snapshot",
        ["social_account_id", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_table(
        "collaboration",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("tier_id", sa.Uuid(), nullable=False),
        sa.Column(
            "required_format",
            sa.Enum(
                "story",
                "post",
                "reel",
                name="content_format",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("required_mention", sa.Text(), nullable=True),
        sa.Column("required_geotag", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "submitted",
                "under_review",
                "approved",
                "resubmit_requested",
                "unfulfilled",
                name="collaboration_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempts_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "needs_human_review", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts_count >= 0", name=op.f("ck_collaboration_attempts_count_positive")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["booking.id"],
            name=op.f("fk_collaboration_booking_id_booking"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tier_id"],
            ["tier.id"],
            name=op.f("fk_collaboration_tier_id_tier"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collaboration")),
        sa.UniqueConstraint("booking_id", name=op.f("uq_collaboration_booking_id")),
    )
    op.create_index(
        "ix_collaboration_needs_human_review", "collaboration", ["needs_human_review"], unique=False
    )
    op.create_index(
        "ix_collaboration_status_deadline_at",
        "collaboration",
        ["status", "deadline_at"],
        unique=False,
    )
    op.create_table(
        "redemption_code",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("secret", sa.LargeBinary(), nullable=False),
        sa.Column("manual_code", sa.Text(), nullable=False),
        sa.Column("rotation_seconds", sa.Integer(), server_default=sa.text("30"), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_by_user_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "rotation_seconds > 0", name=op.f("ck_redemption_code_rotation_seconds_positive")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["booking.id"],
            name=op.f("fk_redemption_code_booking_id_booking"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["consumed_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_redemption_code_consumed_by_user_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_redemption_code")),
        sa.UniqueConstraint("booking_id", name=op.f("uq_redemption_code_booking_id")),
        sa.UniqueConstraint("manual_code", name=op.f("uq_redemption_code_manual_code")),
    )
    op.create_table(
        "reliability_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "collab_completed",
                "published_on_time",
                "published_late",
                "first_pass_compliant",
                "resubmit_required",
                "no_show",
                "unfulfilled",
                "business_rating",
                name="reliability_event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("weight", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["booking.id"],
            name=op.f("fk_reliability_event_booking_id_booking"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator_profile.user_id"],
            name=op.f("fk_reliability_event_creator_id_creator_profile"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reliability_event")),
    )
    op.create_index(
        "ix_reliability_event_creator_id_occurred_at",
        "reliability_event",
        ["creator_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_table(
        "proof",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collaboration_id", sa.Uuid(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column(
            "capture_method",
            sa.Enum(
                "api",
                "url_fetch",
                "upload",
                name="capture_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("media_key", sa.Text(), nullable=True),
        sa.Column("screenshot_key", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("platform_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "media_key IS NOT NULL OR screenshot_key IS NOT NULL",
            name=op.f("ck_proof_has_archived_file"),
        ),
        sa.ForeignKeyConstraint(
            ["collaboration_id"],
            ["collaboration.id"],
            name=op.f("fk_proof_collaboration_id_collaboration"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proof")),
    )
    op.create_index(
        "ix_proof_collaboration_id_submitted_at",
        "proof",
        ["collaboration_id", sa.literal_column("submitted_at DESC")],
        unique=False,
    )
    op.create_index("ix_proof_content_hash", "proof", ["content_hash"], unique=False)
    # ### end Alembic commands ###

    op.execute(AUDIT_LOG_IMMUTABILITY)


def downgrade() -> None:
    """Downgrade schema."""
    # Les triggers disparaissent avec la table, pas la fonction.
    op.execute("DROP FUNCTION IF EXISTS audit_log_reject_mutation() CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_proof_content_hash", table_name="proof")
    op.drop_index("ix_proof_collaboration_id_submitted_at", table_name="proof")
    op.drop_table("proof")
    op.drop_index("ix_reliability_event_creator_id_occurred_at", table_name="reliability_event")
    op.drop_table("reliability_event")
    op.drop_table("redemption_code")
    op.drop_index("ix_collaboration_status_deadline_at", table_name="collaboration")
    op.drop_index("ix_collaboration_needs_human_review", table_name="collaboration")
    op.drop_table("collaboration")
    op.drop_index(
        "ix_social_metrics_snapshot_account_captured", table_name="social_metrics_snapshot"
    )
    op.drop_table("social_metrics_snapshot")
    op.drop_index("ix_booking_status_hold_expires_at", table_name="booking")
    op.drop_index("ix_booking_creator_id_created_at", table_name="booking")
    op.drop_index("ix_booking_business_id_starts_at", table_name="booking")
    op.drop_table("booking")
    op.drop_index("ix_tier_offer_tier_id_is_active", table_name="tier_offer")
    op.drop_table("tier_offer")
    op.drop_index("ix_social_account_creator_id", table_name="social_account")
    op.drop_table("social_account")
    op.drop_index("ix_subscription_business_id", table_name="subscription")
    op.drop_table("subscription")
    op.drop_index("ix_menu_import_business_id_status", table_name="menu_import")
    op.drop_table("menu_import")
    op.drop_index("ix_creator_profile_geo", table_name="creator_profile", postgresql_using="gist")
    op.drop_table("creator_profile")
    op.drop_index("ix_catalog_item_business_id_is_available", table_name="catalog_item")
    op.drop_table("catalog_item")
    op.drop_index("ix_capacity_rule_business_id_weekday", table_name="capacity_rule")
    op.drop_table("capacity_rule")
    op.drop_table("capacity_exception")
    op.drop_table("business_member")
    op.drop_index("ix_audit_log_entity_type_entity_id_occurred_at", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("tier")
    op.drop_table("subscription_plan")
    op.drop_index("ix_business_geo", table_name="business", postgresql_using="gist")
    op.drop_index("ix_business_category_status", table_name="business")
    op.drop_table("business")
    op.drop_index("uq_app_user_email_lower", table_name="app_user")
    op.drop_table("app_user")
    # ### end Alembic commands ###

    # L'extension postgis n'est volontairement pas supprimée : elle peut être
    # partagée avec d'autres schémas de la même base, et la reposer coûte cher.
