"""suppression de compte differee

Revision ID: c9ddb3eb1e67
Revises: 06414f7f41d4
Create Date: 2026-08-19 21:24:19.402882+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9ddb3eb1e67"
down_revision: Union[str, Sequence[str], None] = "06414f7f41d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_user", sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "app_user", sa.Column("deletion_effective_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_check_constraint(
        op.f("ck_app_user_deletion_dates_together"),
        "app_user",
        "(deletion_requested_at IS NULL) = (deletion_effective_at IS NULL)",
    )
    # ### end Alembic commands ###

    # **À la main, et l'autogénération ne le trouve pas.** Une énumération
    # applicative se rend en VARCHAR + CHECK : ajouter une valeur ne change
    # aucune colonne, et la comparaison de schéma ne lit pas la liste. Sans ces
    # lignes, le planificateur ne peut pas créer le balayage et le travail de
    # fond échoue au démarrage — c'est la contrainte qui l'a dit, en test, et
    # c'est exactement son emploi.
    op.drop_constraint("job_type", "job", type_="check")
    op.create_check_constraint(
        "job_type",
        "job",
        "job_type IN ('token_refresh', 'metrics_refresh', 'booking_hold_sweep', 'collaboration_deadline_sweep', 'collaboration_reminder_sweep', 'link_click_purge_sweep', 'subscription_grace_sweep', 'outbox_sweep', 'account_deletion_sweep')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Le job part avant la contrainte qui l'autorise, sinon la nouvelle liste
    # refuserait une ligne déjà écrite.
    op.execute("DELETE FROM job WHERE job_type = 'account_deletion_sweep'")
    op.drop_constraint("job_type", "job", type_="check")
    op.create_check_constraint(
        "job_type",
        "job",
        "job_type IN ('token_refresh', 'metrics_refresh', 'booking_hold_sweep', 'collaboration_deadline_sweep', 'collaboration_reminder_sweep', 'link_click_purge_sweep', 'subscription_grace_sweep', 'outbox_sweep')",
    )
    op.drop_constraint(op.f("ck_app_user_deletion_dates_together"), "app_user", type_="check")
    op.drop_column("app_user", "deletion_effective_at")
    op.drop_column("app_user", "deletion_requested_at")
    # ### end Alembic commands ###
