"""coherence des exceptions de capacite

Revision ID: dc8a03ef1017
Revises: 19d77e87cf45
Create Date: 2026-08-06 01:01:58.453385+00:00

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "dc8a03ef1017"
down_revision: Union[str, Sequence[str], None] = "19d77e87cf45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_capacity_exception_closed_has_no_hours"),
        "capacity_exception",
        "is_closed = (start_time IS NULL)",
    )
    op.create_check_constraint(
        op.f("ck_capacity_exception_closed_has_no_slots"),
        "capacity_exception",
        "NOT is_closed OR concurrent_slots IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_capacity_exception_closed_has_no_slots"), "capacity_exception", type_="check"
    )
    op.drop_constraint(
        op.f("ck_capacity_exception_closed_has_no_hours"), "capacity_exception", type_="check"
    )
    # ### end Alembic commands ###
