"""une note libre attachee au motif et a la soumission

`SPEC.md` §4.2 interdisait le texte libre : une phrase ne se traduit pas a
l'affichage, et elle ressortait sur l'ecran de l'arbitre dans la langue de qui
l'avait ecrite. La regle change de forme plutot que de disparaitre.

**Le code reste obligatoire** et porte le sens traduisible. La note ajoute le
detail qu'un code ne peut pas porter, et `ck_audit_log_note_accompagne_un_motif`
interdit qu'elle voyage seule — sans quoi le journal redeviendrait un champ de
saisie libre par la bande.

La note du journal est immuable comme la ligne qui la porte : le trigger qui
refuse tout UPDATE vaut aussi pour elle. Une note ne se corrige pas apres coup,
on en ecrit une autre.

Revision ID: e402f4b9bd04
Revises: eb545e31208c
Create Date: 2026-08-12 16:47:58.001550+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e402f4b9bd04"
down_revision: Union[str, Sequence[str], None] = "eb545e31208c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_log", sa.Column("note", sa.Text(), nullable=True))
    op.create_check_constraint(
        op.f("ck_audit_log_note_accompagne_un_motif"),
        "audit_log",
        "note IS NULL OR reason IS NOT NULL",
    )
    op.create_check_constraint(
        op.f("ck_audit_log_note_bornee"), "audit_log", "note IS NULL OR length(note) <= 500"
    )
    op.add_column("proof", sa.Column("note", sa.Text(), nullable=True))
    op.create_check_constraint(
        op.f("ck_proof_note_bornee"), "proof", "note IS NULL OR length(note) <= 500"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_proof_note_bornee"), "proof", type_="check")
    op.drop_column("proof", "note")
    op.drop_constraint(op.f("ck_audit_log_note_bornee"), "audit_log", type_="check")
    op.drop_constraint(op.f("ck_audit_log_note_accompagne_un_motif"), "audit_log", type_="check")
    op.drop_column("audit_log", "note")
    # ### end Alembic commands ###
