"""la couverture verticale

Revision ID: e77b5e5492b3
Revises: 13cf2b9349d9
Create Date: 2026-08-17 13:50:43.501764+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e77b5e5492b3"
down_revision: Union[str, Sequence[str], None] = "13cf2b9349d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("business", sa.Column("cover_portrait_key", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("business", "cover_portrait_key")
    # ### end Alembic commands ###
