"""lien traque par contrepartie et clics sans adresse

Trois tables, et **aucune ne porte d'adresse IP**. C'est la propriete a relire
en premier si cette migration doit un jour etre modifiee : l'adresse sert a
resoudre une ville et a calculer une empreinte, puis disparait avec la requete.

`link_click_salt` porte le sel du jour, tire au hasard. C'est lui qui rend
l'oubli definitif : le sel efface, aucune empreinte n'est plus recalculable,
meme en possession de l'adresse d'origine.

`city_geo` est le centre de la ville resolue, identique pour tous ses
habitants. Il situe une ville, jamais quelqu'un. Stocke plutot que reduit a un
booleen « local » parce que le rayon est en configuration, et qu'un booleen
fige cesserait d'etre vrai le jour ou on le change.

Revision ID: eb545e31208c
Revises: 1de11bbfc55d
Create Date: 2026-08-12 15:14:50.913332+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Ajoute a la main : l'autogeneration rend geoalchemy2.types.Geography sans
# importer le module.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "eb545e31208c"
down_revision: Union[str, Sequence[str], None] = "1de11bbfc55d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link_click_salt",
        sa.Column("jour", sa.Date(), nullable=False),
        sa.Column("sel", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("jour", name=op.f("pk_link_click_salt")),
    )
    op.create_table(
        "collaboration_link",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collaboration_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collaboration_id"],
            ["collaboration.id"],
            name=op.f("fk_collaboration_link_collaboration_id_collaboration"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collaboration_link")),
        sa.UniqueConstraint(
            "collaboration_id", name=op.f("uq_collaboration_link_collaboration_id")
        ),
        sa.UniqueConstraint("slug", name=op.f("uq_collaboration_link_slug")),
    )
    op.create_table(
        "link_click",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("link_id", sa.Uuid(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "counted",
                "bot",
                "prefetch",
                "duplicate",
                name="click_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column(
            "city_geo",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "device_family",
            sa.Enum(
                "mobile",
                "tablet",
                "desktop",
                "unknown",
                name="device_family",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("referrer_host", sa.Text(), nullable=True),
        sa.Column("fingerprint", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["collaboration_link.id"],
            name=op.f("fk_link_click_link_id_collaboration_link"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_link_click")),
    )
    op.create_index(
        "ix_link_click_city_geo", "link_click", ["city_geo"], unique=False, postgresql_using="gist"
    )
    op.create_index(
        "ix_link_click_link_id_fingerprint", "link_click", ["link_id", "fingerprint"], unique=False
    )
    op.create_index(
        "ix_link_click_link_id_occurred_at", "link_click", ["link_id", "occurred_at"], unique=False
    )
    op.create_index(
        "ix_link_click_outcome_occurred_at", "link_click", ["outcome", "occurred_at"], unique=False
    )
    # **Le type de job est un VARCHAR + CHECK**, jamais un enum natif : alterer
    # un enum natif en migration est un piege dont ce depot se passe. La
    # contrepartie est qu'ajouter une valeur demande de reecrire la contrainte,
    # ce que l'autogeneration ne detecte pas.
    #
    # Sans cette reecriture, le balayage de purge ne peut pas etre planifie —
    # et la promesse d'oubli tiendrait dans une fonction que personne
    # n'appelle.
    op.drop_constraint(op.f("ck_job_job_type"), "job", type_="check")
    op.create_check_constraint(
        "job_type",
        "job",
        sa.column("job_type").in_(
            [
                "token_refresh",
                "metrics_refresh",
                "booking_hold_sweep",
                "collaboration_deadline_sweep",
                "collaboration_reminder_sweep",
                "link_click_purge_sweep",
            ]
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Les jobs de purge disparaissent avec la contrainte qui les autorisait :
    # les laisser ferait echouer la contrainte restauree.
    op.execute("DELETE FROM job WHERE job_type = 'link_click_purge_sweep'")
    op.drop_constraint(op.f("ck_job_job_type"), "job", type_="check")
    op.create_check_constraint(
        "job_type",
        "job",
        sa.column("job_type").in_(
            [
                "token_refresh",
                "metrics_refresh",
                "booking_hold_sweep",
                "collaboration_deadline_sweep",
                "collaboration_reminder_sweep",
            ]
        ),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_link_click_outcome_occurred_at", table_name="link_click")
    op.drop_index("ix_link_click_link_id_occurred_at", table_name="link_click")
    op.drop_index("ix_link_click_link_id_fingerprint", table_name="link_click")
    op.drop_index("ix_link_click_city_geo", table_name="link_click", postgresql_using="gist")
    op.drop_table("link_click")
    op.drop_table("collaboration_link")
    op.drop_table("link_click_salt")
    # ### end Alembic commands ###
