"""jetons de terminal et preferences de notification

Un jeton de terminal se revoque comme un jeton social : il cesse de valoir sans
nous prevenir, et c'est le fournisseur qui nous l'apprend au moment ou l'on
essaie de s'en servir. Il se marque, il ne se supprime pas — efface, le meme
jeton se reinscrirait a la premiere ouverture et on ne saurait jamais qu'il
avait cesse de valoir.

La table des preferences ne porte que les refus explicites. L'absence vaut
« oui », interpretee par le service : ecrire sept lignes par utilisateur a
l'inscription en ferait sept dont personne ne changera jamais aucune.

Revision ID: f2c893cd716a
Revises: e402f4b9bd04
Create Date: 2026-08-12 18:26:42.581114+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2c893cd716a"
down_revision: Union[str, Sequence[str], None] = "e402f4b9bd04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_token",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "ios",
                "android",
                "web",
                name="device_platform",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "revoked",
                name="device_token_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'revoked') = (revoked_at IS NOT NULL)",
            name=op.f("ck_device_token_revoked_has_date"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_device_token_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_token")),
        sa.UniqueConstraint("token", name=op.f("uq_device_token_token")),
    )
    op.create_index(
        "ix_device_token_user_id_status", "device_token", ["user_id", "status"], unique=False
    )
    op.create_table(
        "notification_preference",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "booking_approved",
                "booking_declined",
                "booking_cancelled_by_business",
                "publication_reminder",
                "publication_approved",
                "publication_resubmit",
                "booking_to_review",
                name="notification_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_notification_preference_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "kind", name=op.f("pk_notification_preference")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_preference")
    op.drop_index("ix_device_token_user_id_status", table_name="device_token")
    op.drop_table("device_token")
    # ### end Alembic commands ###
