"""mode du fournisseur sur le compte social

Revision ID: fa1b037aa08e
Revises: 7325515d6c1a
Create Date: 2026-08-08 03:27:49.820425+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa1b037aa08e"
down_revision: Union[str, Sequence[str], None] = "7325515d6c1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("social_account", sa.Column("provider_mode", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("social_account", "provider_mode")
    # ### end Alembic commands ###
