"""La fiche preparee sur le terrain et sa prise en main

Revision ID: fbfafa1993ee
Revises: 3a85195ca1f5
Create Date: 2026-08-13 03:46:53.708410+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbfafa1993ee"
down_revision: Union[str, Sequence[str], None] = "3a85195ca1f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_handover",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "qr", "email", name="handover_channel", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("destination", sa.Text(), nullable=True),
        sa.Column("issued_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("accepted_terms_version", sa.Text(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(used_at IS NULL) = (used_by_user_id IS NULL AND accepted_terms_version IS NULL)",
            name=op.f("ck_business_handover_prise_en_main_a_son_auteur_et_sa_version"),
        ),
        sa.CheckConstraint(
            "expires_at > issued_at", name=op.f("ck_business_handover_expire_apres_emission")
        ),
        sa.CheckConstraint(
            "used_at IS NULL OR revoked_at IS NULL",
            name=op.f("ck_business_handover_pas_utilise_et_revoque_a_la_fois"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
            name=op.f("fk_business_handover_business_id_business"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_business_handover_issued_by_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["used_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_business_handover_used_by_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_handover")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_business_handover_token_hash")),
    )
    op.create_index(
        "ix_business_handover_business_id_issued_at",
        "business_handover",
        ["business_id", "issued_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # **Écrit à la main, et l'autogénération ne l'a pas vu.** Les énumérations
    # applicatives sont rendues en VARCHAR + CHECK, jamais en type natif :
    # ajouter une valeur ne change aucune colonne, seulement la liste d'une
    # contrainte, et rien dans la comparaison de schémas ne le détecte. Sans
    # ces quatre lignes, la première fiche préparée serait refusée par la base.
    op.drop_constraint("business_status", "business", type_="check")
    op.create_check_constraint(
        "business_status",
        "business",
        "status IN ('draft', 'onboarding', 'active', 'suspended')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_business_handover_business_id_issued_at", table_name="business_handover")
    op.drop_table("business_handover")
    # ### end Alembic commands ###

    # Les fiches préparées redeviennent des inscriptions en cours plutôt que de
    # faire échouer la contrainte : redescendre ne doit pas demander de choisir
    # quelles lignes supprimer. `onboarding` est le voisin le plus proche —
    # invisible du fil, comme `draft`.
    op.execute("UPDATE business SET status = 'onboarding' WHERE status = 'draft'")
    op.drop_constraint("business_status", "business", type_="check")
    op.create_check_constraint(
        "business_status",
        "business",
        "status IN ('onboarding', 'active', 'suspended')",
    )
